apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencryptvolume
  labels:
    io.kompose.service: letsencryptvolume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn  # implement longhorn
  resources:
    requests:
      storage: 1Gi