apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websitevolume
spec:
  storageClassName: longhorn  # implement longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi 