apiVersion: v1
kind: Service
metadata:  
  labels:
    name: openemr
  name: openemr
spec:
  type: LoadBalancer
  ports:
  - name: "https"
    port: 8090
    targetPort: 443
  selector:
    name: openemr
